# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_DATABASE: quarkus-database
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db

  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: ghcr.io/woraamy/kubernates-quarkus-example-project/quarkus
    ports:
      - "8080:8080"
    environment:
      QUARKUS_MONGODB_HOSTS: mongo:27017
#      QUARKUS_MONGODB_USERNAME: root
#      QUARKUS_MONGODB_PASSWORD: example
#      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://root:example@mongo:27017/quarkus-database?authSource=admin

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    image: ghcr.io/woraamy/kubernates-quarkus-example-project/fastapi
    ports:
      - 5000:5000
    environment:
      PERSON_SERVICE_URL: http://quarkus:8080
      DATABASE_URL: mongodb://root:example@mongo:27017/quarkus-database
    depends_on:
      - mongo


#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo:
