apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kubernates-quarkus-example-project-default: "true"
        io.kompose.service: fastapi
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://root:example@mongo:27017/quarkus-database
            - name: PERSON_SERVICE_URL
              value: http://quarkus:8080
          image: fastapi
          name: fastapi
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always
