apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: quarkus
  name: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quarkus
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kubernates-quarkus-example-project-default: "true"
        io.kompose.service: quarkus
    spec:
      containers:
        - env:
            - name: QUARKUS_MONGODB_HOSTS
              value: mongo:27017
          image: quarkus
          name: quarkus
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
