# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/proto/people_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#src/main/proto/people_service.proto\x12\x06person\"\x07\n\x05\x45mpty\"\x1d\n\x0fPersonIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\rPersonRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x62irth\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"H\n\x13UpdatePersonRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x06person\x18\x02 \x01(\x0b\x32\x15.person.PersonRequest\"\x1e\n\x10PersonIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\"5\n\nPersonList\x12\'\n\x07persons\x18\x01 \x03(\x0b\x32\x16.person.PersonResponse\"V\n\x0ePersonResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62irth\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\"\x1d\n\rSearchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\xa9\x03\n\rPeopleService\x12\x30\n\x0bListPersons\x12\r.person.Empty\x1a\x12.person.PersonList\x12<\n\tGetPerson\x12\x17.person.PersonIdRequest\x1a\x16.person.PersonResponse\x12?\n\x0c\x43reatePerson\x12\x15.person.PersonRequest\x1a\x18.person.PersonIdResponse\x12:\n\x0cUpdatePerson\x12\x1b.person.UpdatePersonRequest\x1a\r.person.Empty\x12\x36\n\x0c\x44\x65letePerson\x12\x17.person.PersonIdRequest\x1a\r.person.Empty\x12=\n\x0cSearchPerson\x12\x15.person.SearchRequest\x1a\x16.person.PersonResponse\x12\x34\n\x0c\x43ountPersons\x12\r.person.Empty\x1a\x15.person.CountResponseB,\n\x14org.acme.entity.grpcB\x12PersonServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.main.proto.people_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.acme.entity.grpcB\022PersonServiceProtoP\001'
  _globals['_EMPTY']._serialized_start=47
  _globals['_EMPTY']._serialized_end=54
  _globals['_PERSONIDREQUEST']._serialized_start=56
  _globals['_PERSONIDREQUEST']._serialized_end=85
  _globals['_PERSONREQUEST']._serialized_start=87
  _globals['_PERSONREQUEST']._serialized_end=160
  _globals['_UPDATEPERSONREQUEST']._serialized_start=162
  _globals['_UPDATEPERSONREQUEST']._serialized_end=234
  _globals['_PERSONIDRESPONSE']._serialized_start=236
  _globals['_PERSONIDRESPONSE']._serialized_end=266
  _globals['_PERSONLIST']._serialized_start=268
  _globals['_PERSONLIST']._serialized_end=321
  _globals['_PERSONRESPONSE']._serialized_start=323
  _globals['_PERSONRESPONSE']._serialized_end=409
  _globals['_SEARCHREQUEST']._serialized_start=411
  _globals['_SEARCHREQUEST']._serialized_end=440
  _globals['_COUNTRESPONSE']._serialized_start=442
  _globals['_COUNTRESPONSE']._serialized_end=472
  _globals['_PEOPLESERVICE']._serialized_start=475
  _globals['_PEOPLESERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
