name: Functions Container Build

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*'

jobs:
  fastapi-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/fastapi
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }},priority=1000
            type=ref,event=branch,enable=true,priority=600
            type=ref,event=tag,enable=true,priority=600
            type=ref,event=pr,prefix=pr-,enable=true,priority=600
      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: fastapi
          push: ${{ github.event_name != 'pull_request' && ! startsWith(github.ref_name, 'dependabot')}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  quarkus-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CONTAINER_PUSH: ${{ github.event_name != 'pull_request' && !startsWith(github.ref_name, 'dependabot')}}
      BASE_IMAGE: eclipse-temurin:21-jre
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: 'maven'
      - name: set container tag
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "TAG=:latest" >> "$GITHUB_ENV"
          else
            echo "TAG=:${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          fi
          CI_REGISTRY_IMAGE=ghcr.io/$GITHUB_REPOSITORY
          echo "CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE,,}" >> "$GITHUB_ENV"

      - name: Build and push container image (platforms)
        if: env.CONTAINER_PUSH
        run: mvn -B -DskipTests package --file pom.xml -Dquarkus.container-image.image=ghcr.io/${{ github.repository }}/quarkus${{TAG}} -Dquarkus.container-image.username=${{ github.actor }} -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true